version: '3'
services:
  entrypoint:
    build: ./entrypoint
    network_mode: host

  sensor-nivel-agua:
    build: ./sensor-nivel-agua
    network_mode: host
    environment:
      SENSOR_NAME: "Nível de água 1"
  
  sensor-temperatura:
    build: ./sensor-temperatura
    network_mode: host
    environment:
      SENSOR_NAME: "Temperatura 1"